services:
  - type: web
    name: gyantrix-academy-backend
    plan: free
    runtime: docker

    buildCommand: |
      export JAVA_HOME=/usr/lib/jvm/java-17
      chmod +x mvnw
      ./mvnw clean package -DskipTests

    startCommand: |
      java -jar target/*.jar

    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
